### ISSUE TITLE
Install instructions here do not match with website

### ISSUE THREAD

**Issue by Didddy** [tolgee/ngx-example#232]
see https://tolgee.io/integrations/angular/

**Comment by JanCizmar** [comment]
Hi there. This is example app, where the packages to install are already stored in package.json. The instructions on the web are for project where Tolgee is not yet installed.

**Comment by Didddy** [comment]
Thx for the fast reply -> the website says API key goes to module but app has it in environments file?

**Comment by JanCizmar** [comment]
The website shows super minimal integration example. Since you don't want to leak the API key, you shouldn't push it to git. So you would use the environment file, which is done in this example.

**Comment by Didddy** [comment]
So it works both ways, thx for help!!

**Comment by JanCizmar** [comment]
Yes, but use the env file. Storing the API key in the `app.module` is bad practise and should be used only in demos. :)
